POST http://localhost:8080/event
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNjk5MjgyOTI5LCJ1c2VySWQiOjJ9.7XsczbLX9dN2HocDsumtpQU6Rhvy_jbPTxL2YzbqCqA


{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}